### ISSUE TITLE
Question: Why StartToken is "$" and EndToken is "^"?

### ISSUE THREAD

**Issue by PicoSushi** [mb-14/gomarkov#7]
gomarkov is using "$" as `StartToken` and "^" as `EndToken`, but this seems odd for me. Because, in regular expression, "^" means start of line and "$" means end of line. Are there any reasons for this assignment?
https://github.com/mb-14/gomarkov/blob/044dd0dcb5e7875ec824df72259c523d03aa4f49/gomarkov.go#L14-L17

Note: I'm not familiar with Markov Chain's traditional or standard notation.

**Comment by xeger** [comment]
FWIW @PicoSushi I have fixed this issue in my fork.

**Comment by xeger** [comment]
And, @mb-14 has now [fixed the issue](https://github.com/mb-14/gomarkov/commit/9cbdc8df67a89028b3c0ccbb1f31cb8d7e91f208) on this repository. This issue can be closed.
